# Generated by Django 4.0.1 on 2022-01-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='document_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='document_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=30)),
                ('d_description', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='docs')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('d_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securidocs.document_category')),
            ],
        ),
        migrations.CreateModel(
            name='document_security_technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='privillaged_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privillage_status', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securidocs.document_detail')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securidocs.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securidocs.document_detail')),
            ],
        ),
        migrations.AddField(
            model_name='document_detail',
            name='l_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securidocs.login'),
        ),
        migrations.AddField(
            model_name='document_detail',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securidocs.document_security_technique'),
        ),
    ]
