# Generated by Django 4.0.1 on 2022-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securidocs', '0002_registration_remove_login_name_remove_login_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.AddField(
            model_name='login',
            name='first_name',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='last_name',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
