# Generated by Django 4.0.1 on 2022-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securidocs', '0003_remove_registration_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.AlterField(
            model_name='document_detail',
            name='d_type',
            field=models.CharField(max_length=40),
        ),
    ]
