# Generated by Django 4.0.1 on 2022-03-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securidocs', '0004_delete_registration_alter_document_detail_d_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='privillaged_document',
            name='demail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
