# Generated by Django 4.0.1 on 2022-03-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securidocs', '0005_privillaged_document_demail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_detail',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
